// ─────────────────────────────────────────────────────────────────────────────
// electron/cli/completions.js — shell completion script builders (W5-t29).
// Pure string generation, Electron-free, CJS. `aether completion <shell>`
// prints one of these to stdout; users source it (e.g. `source <(aether
// completion bash)` / `aether completion powershell | Out-String | Invoke-Expression`).
//
// Keep `allFlags` in sync with the Options section of cli.js HELP text.
// ─────────────────────────────────────────────────────────────────────────────

'use strict'

// Every CLI flag (long form) plus the two subcommands, and --mode values.
const allFlags = [
  '--model', '--provider', '--api-key', '--api-url', '--api-format',
  '--mode', '--workspace', '--max-iterations',
  '--json', '--json-lines', '--task', '--setup-term', '--memory-trace',
  '--skills', '--list-models', '--list-providers', '--db', '--persona',
  '--stdin', '--resume', '--session', '--fork', '--version', '--help',
  '-p', '-o', '-h',
]
const subcommands = ['tui', 'completion']
const modeValues = ['auto', 'plan', 'ask', 'yolo', 'json', 'rpc']

function bashScript() {
  const flags = allFlags.join(' ')
  const subs = subcommands.join(' ')
  const modes = modeValues.join(' ')
  return `# bash completion for aether (generated by \`aether completion bash\`).
# Source it in ~/.bashrc:  source <(aether completion bash)
_aether() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "$prev" == "--mode" ]]; then
    COMPREPLY=( $(compgen -W "${modes}" -- "$cur") )
    return 0
  fi
  COMPREPLY=( $(compgen -W "${flags} ${subs}" -- "$cur") )
  return 0
}
complete -F _aether aether
`
}

function zshScript() {
  const flags = allFlags.map((f) => `'${f}'`).join(' ')
  const modes = modeValues.join(' ')
  return `#compdef aether
# zsh completion for aether (generated by \`aether completion zsh\`).
# Place in a directory on your $fpath as _aether, or source it directly.
_aether() {
  local -a opts
  opts=(${flags} ${subcommands})
  if [[ $words[$CURRENT-1] == '--mode' ]]; then
    compadd ${modes}
  else
    compadd -a opts
  fi
}
compdef _aether aether
`
}

function powershellScript() {
  const flags = allFlags.map((f) => `'${f}'`).join(', ')
  const modes = modeValues.map((m) => `'${m}'`).join(', ')
  return `# PowerShell completion for aether (generated by \`aether completion powershell\`).
# Add to your $PROFILE:  aether completion powershell | Out-String | Invoke-Expression
Register-ArgumentCompleter -Native -CommandName aether -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $flags = @(${flags})
  $modeValues = @(${modes})
  $prev = if ($commandAst.CommandElements.Count -ge 2) {
    $commandAst.CommandElements[$commandAst.CommandElements.Count - 2].Extent.Text
  } else { '' }
  $candidates = if ($prev -eq '--mode') { $modeValues } else { $flags }
  $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }
}
`
}

const SHELLS = ['bash', 'zsh', 'powershell']

/**
 * Build the completion script for a shell.
 * @param {string} shell  'bash' | 'zsh' | 'powershell' (default 'bash')
 * @returns {{ok: true, script: string} | {ok: false, error: string}}
 */
function scriptFor(shell) {
  const name = String(shell || 'bash').toLowerCase()
  if (name === 'bash') return { ok: true, script: bashScript() }
  if (name === 'zsh') return { ok: true, script: zshScript() }
  if (name === 'powershell') return { ok: true, script: powershellScript() }
  return { ok: false, error: `unknown shell: ${shell} (supported: ${SHELLS.join(', ')})` }
}

module.exports = { allFlags, subcommands, modeValues, bashScript, zshScript, powershellScript, scriptFor, SHELLS }
